import type { Property, User, Booking, Conversation, Message, Review } from '@/types';

export const DEMO_USER: User = {
  id: 'demo-user-1',
  email: 'demo@rentpro.com',
  full_name: 'Alex Demo',
  avatar_url: 'https://images.unsplash.com/photo-1535713875002-d1d0cf377fde?w=200&h=200&fit=crop&crop=face',
  role: 'guest',
  phone: '+1 (555) 000-0000',
  created_at: '2025-01-15T10:00:00Z',
};

export const DEMO_HOST: User = {
  id: 'demo-host-1',
  email: 'host@rentpro.com',
  full_name: 'Maria Rodriguez',
  avatar_url: 'https://images.unsplash.com/photo-1494790108377-be9c29b29330?w=200&h=200&fit=crop&crop=face',
  role: 'host',
  phone: '+1 (555) 111-1111',
  is_superhost: true,
  created_at: '2024-06-20T10:00:00Z',
};

export const DEMO_PASSWORD = 'demo123';

export const DEMO_PROPERTIES: Property[] = [
  {
    id: 'prop-1',
    host_id: 'demo-host-1',
    title: 'Villa de lujo frente al mar',
    description: 'Espectacular villa con vista panoramica al oceano. Disena para el maximo confort, esta propiedad cuenta con una piscina infinita privada, acceso directo a la playa, y terraza con asador. Perfecta para familias o grupos de amigos que buscan una experiencia de lujo junto al mar.\n\nLa villa tiene 4 habitaciones amplias con aire acondicionado, cada una con bano en suite. La cocina esta totalmente equipada con electrodomesticos de ultima generacion. El area social incluye sala de estar con TV 4K, comedor para 8 personas, y bar privado.\n\nServicios incluidos: WiFi de alta velocidad, limpieza diaria, toallas de playa, y estacionamiento privado.',
    location: 'Miami Beach, Florida',
    city: 'Miami Beach',
    state: 'Florida',
    country: 'USA',
    latitude: 25.7617,
    longitude: -80.1918,
    price_per_night: 350,
    currency: 'USD',
    max_guests: 8,
    bedrooms: 4,
    beds: 5,
    bathrooms: 3.5,
    property_type: 'villa',
    category: 'beach',
    amenities: ['wifi', 'pool', 'ac', 'parking', 'kitchen', 'tv', 'grill', 'workspace'],
    images: [
      '/images/prop1.jpg',
      '/images/prop2.jpg',
      '/images/prop3.jpg',
      '/images/prop4.jpg',
      '/images/prop5.jpg',
    ],
    rating: 4.92,
    review_count: 128,
    is_superhost: true,
    instant_book: true,
    cancellation_policy: 'flexible',
    house_rules: {
      pets_allowed: false,
      smoking_allowed: false,
      events_allowed: true,
      check_in_time: '15:00',
      check_out_time: '11:00',
      min_age: 21,
    },
    created_at: '2024-01-10T10:00:00Z',
    updated_at: '2025-03-15T10:00:00Z',
    host: DEMO_HOST,
  },
  {
    id: 'prop-2',
    host_id: 'demo-host-1',
    title: 'Cabaña acogedora en las montañas',
    description: 'Escapate a esta hermosa cabana rodeada de naturaleza. Con vistas impresionantes a las montañas, chimenea de piedra, y un porche perfecto para relajarse. Ideal para una escapada romantica o un retiro tranquilo.\n\nLa cabana tiene 2 habitaciones, cocina rustica totalmente equipada, y un amplio living room con chimenea. El exterior cuenta con fogata, hamacas, y acceso a senderos naturales.',
    location: 'Asheville, North Carolina',
    city: 'Asheville',
    state: 'North Carolina',
    country: 'USA',
    latitude: 35.5951,
    longitude: -82.5515,
    price_per_night: 185,
    currency: 'USD',
    max_guests: 4,
    bedrooms: 2,
    beds: 2,
    bathrooms: 1,
    property_type: 'cabin',
    category: 'mountain',
    amenities: ['wifi', 'fireplace', 'parking', 'kitchen', 'tv', 'pets_allowed'],
    images: [
      '/images/prop2.jpg',
      '/images/prop3.jpg',
      '/images/prop4.jpg',
    ],
    rating: 4.85,
    review_count: 89,
    is_superhost: true,
    instant_book: false,
    cancellation_policy: 'moderate',
    house_rules: {
      pets_allowed: true,
      smoking_allowed: false,
      events_allowed: false,
      check_in_time: '16:00',
      check_out_time: '10:00',
      min_age: 18,
    },
    created_at: '2024-03-20T10:00:00Z',
    updated_at: '2025-02-10T10:00:00Z',
    host: DEMO_HOST,
  },
  {
    id: 'prop-3',
    host_id: 'demo-host-1',
    title: 'Loft moderno en el centro',
    description: 'Loft de diseno industrial en pleno centro de la ciudad. Techos altos, paredes de ladrillo expuesto, y ventanales panoramicos con vistas al skyline. Perfecto para viajeros de negocios o parejas que quieren estar en el corazon de todo.\n\nEl loft cuenta con una suite principal, oficina con escritorio ejecutivo, cocina gourmet, y balcon privado. El edificio tiene gimnasio y terraza compartida en la azotea.',
    location: 'Manhattan, New York',
    city: 'Manhattan',
    state: 'New York',
    country: 'USA',
    latitude: 40.7128,
    longitude: -74.006,
    price_per_night: 275,
    currency: 'USD',
    max_guests: 2,
    bedrooms: 1,
    beds: 1,
    bathrooms: 1,
    property_type: 'apartment',
    category: 'city',
    amenities: ['wifi', 'ac', 'gym', 'workspace', 'tv', 'kitchen'],
    images: [
      '/images/prop3.jpg',
      '/images/prop4.jpg',
      '/images/prop5.jpg',
    ],
    rating: 4.78,
    review_count: 203,
    is_superhost: false,
    instant_book: true,
    cancellation_policy: 'strict',
    house_rules: {
      pets_allowed: false,
      smoking_allowed: false,
      events_allowed: false,
      check_in_time: '15:00',
      check_out_time: '11:00',
      min_age: 21,
    },
    created_at: '2024-05-15T10:00:00Z',
    updated_at: '2025-04-01T10:00:00Z',
    host: DEMO_HOST,
  },
  {
    id: 'prop-4',
    host_id: 'demo-host-1',
    title: 'Casa rural con jardin privado',
    description: 'Encantadora casa de campo restaurada con jardin privado lleno de flores y frutales. Cocina rustica con horno de lena, porche cubierto con hamacas, y un estanque natural. Experiencia autentica de vida rural.',
    location: 'Napa Valley, California',
    city: 'Napa Valley',
    state: 'California',
    country: 'USA',
    latitude: 38.2975,
    longitude: -122.2869,
    price_per_night: 220,
    currency: 'USD',
    max_guests: 6,
    bedrooms: 3,
    beds: 3,
    bathrooms: 2,
    property_type: 'house',
    category: 'countryside',
    amenities: ['wifi', 'parking', 'kitchen', 'fireplace', 'grill', 'tv', 'pets_allowed'],
    images: [
      '/images/prop4.jpg',
      '/images/prop5.jpg',
      '/images/prop6.jpg',
    ],
    rating: 4.96,
    review_count: 67,
    is_superhost: true,
    instant_book: true,
    cancellation_policy: 'flexible',
    house_rules: {
      pets_allowed: true,
      smoking_allowed: false,
      events_allowed: true,
      check_in_time: '14:00',
      check_out_time: '12:00',
      min_age: 18,
    },
    created_at: '2024-02-28T10:00:00Z',
    updated_at: '2025-03-20T10:00:00Z',
    host: DEMO_HOST,
  },
  {
    id: 'prop-5',
    host_id: 'demo-host-1',
    title: 'Tiny Home entre los arboles',
    description: 'Minimalista y sostenible, esta tiny home esta escondida entre los arboles ofreciendo total privacidad. Ventanales enormes, terraza con vista al bosque, y todas las comodidades en un espacio inteligentemente disenado.',
    location: 'Portland, Oregon',
    city: 'Portland',
    state: 'Oregon',
    country: 'USA',
    latitude: 45.5152,
    longitude: -122.6784,
    price_per_night: 125,
    currency: 'USD',
    max_guests: 2,
    bedrooms: 1,
    beds: 1,
    bathrooms: 1,
    property_type: 'tiny_home',
    category: 'tiny_home',
    amenities: ['wifi', 'kitchen', 'fireplace', 'workspace'],
    images: [
      '/images/prop5.jpg',
      '/images/prop6.jpg',
      '/images/prop1.jpg',
    ],
    rating: 4.88,
    review_count: 145,
    is_superhost: true,
    instant_book: true,
    cancellation_policy: 'flexible',
    house_rules: {
      pets_allowed: false,
      smoking_allowed: false,
      events_allowed: false,
      check_in_time: '15:00',
      check_out_time: '11:00',
      min_age: 18,
    },
    created_at: '2024-06-01T10:00:00Z',
    updated_at: '2025-04-10T10:00:00Z',
    host: DEMO_HOST,
  },
  {
    id: 'prop-6',
    host_id: 'demo-host-1',
    title: 'Penthouse de lujo con vista al oceano',
    description: 'El pinaculo del lujo urbano. Este penthouse en el piso 50 ofrece vistas panoramicas de 360 grados al oceano y la ciudad. Piscina privada en la terraza, sala de cine, y servicio de mayordomo incluido.',
    location: 'South Beach, Miami',
    city: 'Miami Beach',
    state: 'Florida',
    country: 'USA',
    latitude: 25.7907,
    longitude: -80.13,
    price_per_night: 850,
    currency: 'USD',
    max_guests: 6,
    bedrooms: 3,
    beds: 3,
    bathrooms: 3.5,
    property_type: 'apartment',
    category: 'luxury',
    amenities: ['wifi', 'pool', 'ac', 'parking', 'gym', 'hot_tub', 'tv', 'workspace', 'kitchen'],
    images: [
      '/images/prop6.jpg',
      '/images/prop1.jpg',
      '/images/prop2.jpg',
      '/images/prop3.jpg',
      '/images/prop4.jpg',
    ],
    rating: 4.98,
    review_count: 42,
    is_superhost: true,
    instant_book: true,
    cancellation_policy: 'flexible',
    house_rules: {
      pets_allowed: false,
      smoking_allowed: false,
      events_allowed: true,
      check_in_time: '14:00',
      check_out_time: '12:00',
      min_age: 25,
    },
    created_at: '2024-01-05T10:00:00Z',
    updated_at: '2025-04-15T10:00:00Z',
    host: DEMO_HOST,
  },
  {
    id: 'prop-7',
    host_id: 'demo-host-1',
    title: 'Cabana junto al lago',
    description: 'Cabana rustica con acceso privado al lago. Kayaks incluidos, fogata junto al agua, y muelle privado para pesca. Perfecta para desconectar y disfrutar de la naturaleza en familia.',
    location: 'Lake Tahoe, California',
    city: 'Lake Tahoe',
    state: 'California',
    country: 'USA',
    latitude: 39.0968,
    longitude: -120.0324,
    price_per_night: 195,
    currency: 'USD',
    max_guests: 6,
    bedrooms: 2,
    beds: 3,
    bathrooms: 1.5,
    property_type: 'cabin',
    category: 'lakefront',
    amenities: ['wifi', 'fireplace', 'parking', 'kitchen', 'grill', 'tv', 'pets_allowed'],
    images: [
      '/images/prop1.jpg',
      '/images/prop2.jpg',
      '/images/prop3.jpg',
    ],
    rating: 4.91,
    review_count: 76,
    is_superhost: true,
    instant_book: false,
    cancellation_policy: 'moderate',
    house_rules: {
      pets_allowed: true,
      smoking_allowed: false,
      events_allowed: true,
      check_in_time: '16:00',
      check_out_time: '10:00',
      min_age: 18,
    },
    created_at: '2024-04-10T10:00:00Z',
    updated_at: '2025-03-01T10:00:00Z',
    host: DEMO_HOST,
  },
  {
    id: 'prop-8',
    host_id: 'demo-host-1',
    title: 'Casa con piscina privada',
    description: 'Hermosa casa de una planta con gran piscina privada y jardin tropical. Barbacoa exterior, zona de juegos para ninos, y amplio patio. Ideal para familias que buscan sol y diversion.',
    location: 'Orlando, Florida',
    city: 'Orlando',
    state: 'Florida',
    country: 'USA',
    latitude: 28.5383,
    longitude: -81.3792,
    price_per_night: 240,
    currency: 'USD',
    max_guests: 8,
    bedrooms: 4,
    beds: 4,
    bathrooms: 2,
    property_type: 'house',
    category: 'luxury',
    amenities: ['wifi', 'pool', 'ac', 'parking', 'kitchen', 'tv', 'grill'],
    images: [
      '/images/prop4.jpg',
      '/images/prop5.jpg',
      '/images/prop6.jpg',
    ],
    rating: 4.82,
    review_count: 112,
    is_superhost: false,
    instant_book: true,
    cancellation_policy: 'flexible',
    house_rules: {
      pets_allowed: false,
      smoking_allowed: false,
      events_allowed: true,
      check_in_time: '15:00',
      check_out_time: '11:00',
      min_age: 18,
    },
    created_at: '2024-07-15T10:00:00Z',
    updated_at: '2025-04-05T10:00:00Z',
    host: DEMO_HOST,
  },
];

export const DEMO_BOOKINGS: Booking[] = [
  {
    id: 'book-1',
    property_id: 'prop-1',
    guest_id: 'demo-user-1',
    host_id: 'demo-host-1',
    check_in: '2025-05-15',
    check_out: '2025-05-20',
    guests_count: 4,
    total_nights: 5,
    nightly_price: 350,
    cleaning_fee: 50,
    service_fee: 210,
    total_price: 2010,
    currency: 'USD',
    status: 'confirmed',
    payment_status: 'paid',
    created_at: '2025-04-01T10:00:00Z',
    updated_at: '2025-04-01T10:00:00Z',
    property: DEMO_PROPERTIES[0],
    guest: DEMO_USER,
  },
  {
    id: 'book-2',
    property_id: 'prop-4',
    guest_id: 'demo-user-1',
    host_id: 'demo-host-1',
    check_in: '2025-06-10',
    check_out: '2025-06-14',
    guests_count: 2,
    total_nights: 4,
    nightly_price: 220,
    cleaning_fee: 50,
    service_fee: 106,
    total_price: 1036,
    currency: 'USD',
    status: 'pending',
    payment_status: 'pending',
    created_at: '2025-04-10T10:00:00Z',
    updated_at: '2025-04-10T10:00:00Z',
    property: DEMO_PROPERTIES[3],
    guest: DEMO_USER,
  },
  {
    id: 'book-3',
    property_id: 'prop-2',
    guest_id: 'demo-user-1',
    host_id: 'demo-host-1',
    check_in: '2025-03-01',
    check_out: '2025-03-05',
    guests_count: 2,
    total_nights: 4,
    nightly_price: 185,
    cleaning_fee: 50,
    service_fee: 89,
    total_price: 879,
    currency: 'USD',
    status: 'completed',
    payment_status: 'paid',
    created_at: '2025-02-15T10:00:00Z',
    updated_at: '2025-03-05T10:00:00Z',
    property: DEMO_PROPERTIES[1],
    guest: DEMO_USER,
  },
  {
    id: 'book-4',
    property_id: 'prop-3',
    guest_id: 'demo-user-1',
    host_id: 'demo-host-1',
    check_in: '2025-04-20',
    check_out: '2025-04-22',
    guests_count: 2,
    total_nights: 2,
    nightly_price: 275,
    cleaning_fee: 50,
    service_fee: 66,
    total_price: 666,
    currency: 'USD',
    status: 'cancelled',
    payment_status: 'refunded',
    created_at: '2025-03-20T10:00:00Z',
    updated_at: '2025-04-18T10:00:00Z',
    property: DEMO_PROPERTIES[2],
    guest: DEMO_USER,
  },
];

export const DEMO_REVIEWS: Review[] = [
  {
    id: 'rev-1',
    property_id: 'prop-1',
    booking_id: 'book-1',
    reviewer_id: 'demo-user-1',
    reviewee_id: 'demo-host-1',
    rating: 5,
    cleanliness: 5,
    accuracy: 5,
    check_in: 5,
    communication: 5,
    location: 5,
    value: 4,
    comment: 'Increible experiencia! La villa es aun mas hermosa en persona. La piscina infinita es magica al atardecer. Maria fue una anfitriona excepcional, siempre disponible y atenta. Definitivamente volveremos.',
    created_at: '2025-05-25T10:00:00Z',
  },
  {
    id: 'rev-2',
    property_id: 'prop-3',
    booking_id: 'book-3',
    reviewer_id: 'demo-user-1',
    reviewee_id: 'demo-host-1',
    rating: 4,
    cleanliness: 5,
    accuracy: 4,
    check_in: 4,
    communication: 5,
    location: 5,
    value: 4,
    comment: 'El loft es espectacular, muy bien ubicado. Las vistas nocturnas son impresionantes. Solo le doy 4 estrellas porque el ruido de la calle a veces se escucha, pero es algo normal estando en Manhattan.',
    created_at: '2025-03-10T10:00:00Z',
  },
];

export const DEMO_CONVERSATIONS: Conversation[] = [
  {
    id: 'conv-1',
    property_id: 'prop-1',
    guest_id: 'demo-user-1',
    host_id: 'demo-host-1',
    created_at: '2025-04-01T10:00:00Z',
    updated_at: '2025-04-15T14:30:00Z',
    property: DEMO_PROPERTIES[0],
    guest: DEMO_USER,
    host: DEMO_HOST,
    unread_count: 1,
  },
];

export const DEMO_MESSAGES: Message[] = [
  {
    id: 'msg-1',
    conversation_id: 'conv-1',
    sender_id: 'demo-user-1',
    content: 'Hola Maria! Estoy muy emocionado por nuestra reserva en mayo. ¿Podemos llegar un poco antes del check-in?',
    created_at: '2025-04-01T10:05:00Z',
    sender: DEMO_USER,
  },
  {
    id: 'msg-2',
    conversation_id: 'conv-1',
    sender_id: 'demo-host-1',
    content: 'Hola Alex! Claro que si, con gusto. Pueden llegar a partir de las 13:00. Les dejare las llaves en la caja fuerte y les enviare el codigo un dia antes.',
    created_at: '2025-04-01T10:15:00Z',
    sender: DEMO_HOST,
  },
  {
    id: 'msg-3',
    conversation_id: 'conv-1',
    sender_id: 'demo-user-1',
    content: 'Perfecto, muchas gracias! ¿Hay alguna recomendacion de restaurantes cerca?',
    created_at: '2025-04-02T09:00:00Z',
    sender: DEMO_USER,
  },
  {
    id: 'msg-4',
    conversation_id: 'conv-1',
    sender_id: 'demo-host-1',
    content: 'Si! Les recomiendo Joe\'s Stone Crab a 5 minutos caminando por la playa. Tambien hay un cafe excelente para el desayuno justo en la esquina. Les prepare una guia con todas mis recomendaciones locales.',
    created_at: '2025-04-02T09:30:00Z',
    sender: DEMO_HOST,
  },
  {
    id: 'msg-5',
    conversation_id: 'conv-1',
    sender_id: 'demo-host-1',
    content: 'Una cosa mas - la piscina se calienta automaticamente a las 4pm, asi que es perfecta para un chapuzon al atardecer con una copa de vino.',
    created_at: '2025-04-15T14:30:00Z',
    sender: DEMO_HOST,
  },
];
