import type { User, Lead, Job, Contact, CalendarEvent, Document, QuestionnaireTemplate, ActivityLog, DashboardStats } from '@/types';

export const DEMO_USER: User = {
  id: 'user-1',
  email: 'studio@photostudio.com',
  full_name: 'Alex Morgan',
  avatar_url: 'https://images.unsplash.com/photo-1535713875002-d1d0cf377fde?w=200&fit=crop&crop=face',
  role: 'admin',
  studio_name: 'Sparkle Photography',
  created_at: '2024-01-15T10:00:00Z',
};

export const DEMO_USERS: User[] = [
  DEMO_USER,
  {
    id: 'user-2',
    email: 'sarah@photostudio.com',
    full_name: 'Sarah Chen',
    avatar_url: 'https://images.unsplash.com/photo-1494790108377-be9c29b29330?w=200&fit=crop&crop=face',
    role: 'photographer',
    studio_name: 'Sparkle Photography',
    created_at: '2024-03-10T10:00:00Z',
  },
  {
    id: 'user-3',
    email: 'mike@photostudio.com',
    full_name: 'Mike Johnson',
    avatar_url: 'https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?w=200&fit=crop&crop=face',
    role: 'editor',
    studio_name: 'Sparkle Photography',
    created_at: '2024-06-20T10:00:00Z',
  },
];

export const DEMO_LEADS: Lead[] = [
  {
    id: 'lead-1',
    name: 'Jessica & David',
    email: 'jessica@example.com',
    phone: '(555) 123-4567',
    shoot_type: 'wedding',
    status: 'new',
    priority: 'high',
    event_date: '2025-09-20',
    budget: 3500,
    notes: 'Wedding at The Grand Ballroom. 150 guests. Want both photo and video.',
    source: 'Instagram',
    assigned_to: 'user-1',
    created_at: '2025-04-20T10:00:00Z',
    updated_at: '2025-04-20T10:00:00Z',
    tags: ['premium', 'referral'],
  },
  {
    id: 'lead-2',
    name: 'Emma Thompson',
    email: 'emma.t@example.com',
    shoot_type: 'senior',
    status: 'qualified',
    priority: 'medium',
    event_date: '2025-06-15',
    budget: 450,
    notes: 'Senior portrait for graduation. Wants outdoor session at park.',
    source: 'Google',
    assigned_to: 'user-2',
    created_at: '2025-04-18T14:30:00Z',
    updated_at: '2025-04-19T09:00:00Z',
    tags: ['senior-session'],
  },
  {
    id: 'lead-3',
    name: 'The Rodriguez Family',
    email: 'rodriguez.family@example.com',
    phone: '(555) 987-6543',
    shoot_type: 'family',
    status: 'proposal_sent',
    priority: 'medium',
    event_date: '2025-07-04',
    budget: 800,
    notes: 'Family reunion photos. 12 people including grandparents. Beach location preferred.',
    source: 'Referral',
    assigned_to: 'user-1',
    created_at: '2025-04-15T11:00:00Z',
    updated_at: '2025-04-22T16:00:00Z',
    tags: ['family', 'outdoor'],
  },
  {
    id: 'lead-4',
    name: 'Mark & Lisa',
    email: 'mark.lisa@example.com',
    shoot_type: 'engagement',
    status: 'contract_signed',
    priority: 'high',
    event_date: '2025-05-25',
    budget: 1200,
    notes: 'Engagement shoot at botanical gardens. Want golden hour photos.',
    source: 'Facebook',
    assigned_to: 'user-2',
    created_at: '2025-04-10T09:00:00Z',
    updated_at: '2025-04-25T10:00:00Z',
    tags: ['engagement', 'outdoor'],
  },
  {
    id: 'lead-5',
    name: 'Rachel Green',
    email: 'rachel.g@example.com',
    phone: '(555) 234-5678',
    shoot_type: 'maternity',
    status: 'active_job',
    priority: 'high',
    event_date: '2025-05-10',
    budget: 650,
    notes: 'Maternity shoot at 32 weeks. Studio session with floral backdrop.',
    source: 'Website',
    assigned_to: 'user-1',
    created_at: '2025-04-05T13:00:00Z',
    updated_at: '2025-04-28T14:00:00Z',
    tags: ['maternity', 'studio'],
  },
  {
    id: 'lead-6',
    name: 'Corporate Event Inc.',
    email: 'events@corporate.com',
    shoot_type: 'event',
    status: 'new',
    priority: 'low',
    event_date: '2025-08-15',
    budget: 2000,
    notes: 'Annual company gala. Need event coverage for 200+ attendees.',
    source: 'Email',
    assigned_to: 'user-3',
    created_at: '2025-04-22T08:00:00Z',
    updated_at: '2025-04-22T08:00:00Z',
    tags: ['corporate', 'event'],
  },
  {
    id: 'lead-7',
    name: 'Baby Carter',
    email: 'carter.family@example.com',
    shoot_type: 'portrait',
    status: 'qualified',
    priority: 'medium',
    event_date: '2025-06-01',
    budget: 350,
    notes: 'Newborn session. Baby will be 2 weeks old. Family wants lifestyle style.',
    source: 'Referral',
    assigned_to: 'user-2',
    created_at: '2025-04-19T10:00:00Z',
    updated_at: '2025-04-23T11:00:00Z',
    tags: ['newborn', 'lifestyle'],
  },
  {
    id: 'lead-8',
    name: 'Fashion Brand Co.',
    email: 'creative@fashion.com',
    shoot_type: 'commercial',
    status: 'proposal_sent',
    priority: 'urgent',
    event_date: '2025-05-30',
    budget: 5000,
    notes: 'Product photography for summer collection. Need 50+ images. Studio lighting.',
    source: 'Instagram',
    assigned_to: 'user-1',
    created_at: '2025-04-12T15:00:00Z',
    updated_at: '2025-04-24T09:00:00Z',
    tags: ['commercial', 'product'],
  },
];

export const DEMO_JOBS: Job[] = [
  {
    id: 'job-1',
    lead_id: 'lead-5',
    client_name: 'Rachel Green',
    shoot_type: 'maternity',
    status: 'in_progress',
    event_date: '2025-05-10',
    delivery_date: '2025-05-24',
    location: 'Studio A',
    package_name: 'Maternity Deluxe',
    price: 650,
    deposit: 200,
    balance: 450,
    notes: '32-week session. Floral backdrop confirmed.',
    assigned_to: 'user-1',
    created_at: '2025-04-28T14:00:00Z',
    updated_at: '2025-04-28T14:00:00Z',
    tags: ['maternity', 'studio'],
  },
  {
    id: 'job-2',
    lead_id: 'lead-4',
    client_name: 'Mark & Lisa',
    shoot_type: 'engagement',
    status: 'pending',
    event_date: '2025-05-25',
    location: 'Botanical Gardens',
    package_name: 'Engagement Classic',
    price: 1200,
    deposit: 400,
    balance: 800,
    notes: 'Golden hour preferred. Bring reflectors.',
    assigned_to: 'user-2',
    created_at: '2025-04-25T10:00:00Z',
    updated_at: '2025-04-25T10:00:00Z',
    tags: ['engagement', 'outdoor'],
  },
  {
    id: 'job-3',
    lead_id: 'lead-2',
    client_name: 'Emma Thompson',
    shoot_type: 'senior',
    status: 'editing',
    event_date: '2025-04-15',
    delivery_date: '2025-05-01',
    location: 'Riverside Park',
    package_name: 'Senior Session',
    price: 450,
    deposit: 150,
    balance: 300,
    notes: 'Outdoor session completed. 200+ raw images. Editing in progress.',
    assigned_to: 'user-2',
    created_at: '2025-04-15T14:30:00Z',
    updated_at: '2025-04-26T16:00:00Z',
    tags: ['senior', 'outdoor'],
  },
  {
    id: 'job-4',
    lead_id: 'lead-1',
    client_name: 'Jessica & David',
    shoot_type: 'wedding',
    status: 'pending',
    event_date: '2025-09-20',
    location: 'The Grand Ballroom',
    package_name: 'Wedding Premium',
    price: 3500,
    deposit: 1000,
    balance: 2500,
    notes: 'Full day coverage. Second shooter needed.',
    assigned_to: 'user-1',
    created_at: '2025-04-20T10:00:00Z',
    updated_at: '2025-04-20T10:00:00Z',
    tags: ['wedding', 'premium'],
  },
];

export const DEMO_CONTACTS: Contact[] = [
  { id: 'c1', type: 'client', name: 'Jessica & David', email: 'jessica@example.com', phone: '(555) 123-4567', notes: 'Wedding client - Sept 2025', tags: ['wedding'], created_at: '2025-04-20T10:00:00Z' },
  { id: 'c2', type: 'client', name: 'Emma Thompson', email: 'emma.t@example.com', phone: '(555) 222-3333', notes: 'Senior portraits', tags: ['senior'], created_at: '2025-04-18T14:30:00Z' },
  { id: 'c3', type: 'vendor', name: 'Grand Ballroom Venue', email: 'events@grandballroom.com', phone: '(555) 444-5555', company: 'Grand Ballroom Events', address: '123 Main St', notes: 'Preferred venue partner', tags: ['venue'], created_at: '2025-01-10T10:00:00Z' },
  { id: 'c4', type: 'vendor', name: 'Floral Designs by Maria', email: 'maria@floral.com', phone: '(555) 666-7777', company: 'Floral Designs', notes: 'Wedding florist', tags: ['florist'], created_at: '2025-02-15T10:00:00Z' },
  { id: 'c5', type: 'referral', name: 'Sarah Chen', email: 'sarah@photostudio.com', phone: '(555) 888-9999', company: 'Sparkle Photography', notes: 'Associate photographer', tags: ['photographer'], created_at: '2024-03-10T10:00:00Z' },
  { id: 'c6', type: 'prospect', name: 'Fashion Brand Co.', email: 'creative@fashion.com', notes: 'Commercial prospect', tags: ['commercial'], created_at: '2025-04-12T15:00:00Z' },
];

export const DEMO_EVENTS: CalendarEvent[] = [
  { id: 'e1', title: 'Maternity Session - Rachel', date: '2025-05-10T10:00:00Z', type: 'shoot', client_name: 'Rachel Green', location: 'Studio A', duration_minutes: 120, color: '#06b6d4', notes: '32-week session' },
  { id: 'e2', title: 'Engagement - Mark & Lisa', date: '2025-05-25T17:00:00Z', type: 'shoot', client_name: 'Mark & Lisa', location: 'Botanical Gardens', duration_minutes: 90, color: '#f59e0b', notes: 'Golden hour' },
  { id: 'e3', title: 'Client Meeting - Rodriguez', date: '2025-05-05T14:00:00Z', type: 'meeting', client_name: 'The Rodriguez Family', duration_minutes: 30, color: '#8b5cf6' },
  { id: 'e4', title: 'Photo Delivery - Emma', date: '2025-05-01T09:00:00Z', type: 'delivery', client_name: 'Emma Thompson', duration_minutes: 60, color: '#10b981' },
  { id: 'e5', title: 'Team Review', date: '2025-05-03T10:00:00Z', type: 'personal', duration_minutes: 60, color: '#64748b' },
];

export const DEMO_DOCUMENTS: Document[] = [
  { id: 'd1', name: 'Wedding Contract - Jessica & David', type: 'contract', client_name: 'Jessica & David', size: '245 KB', created_at: '2025-04-20T10:00:00Z' },
  { id: 'd2', name: 'Invoice #2045 - Emma Thompson', type: 'invoice', client_name: 'Emma Thompson', size: '128 KB', created_at: '2025-04-15T14:30:00Z' },
  { id: 'd3', name: 'Engagement Gallery - Mark & Lisa', type: 'gallery', client_name: 'Mark & Lisa', size: '1.2 GB', created_at: '2025-04-25T10:00:00Z' },
  { id: 'd4', name: 'Pre-Session Questionnaire', type: 'questionnaire', client_name: 'Rachel Green', size: '56 KB', created_at: '2025-04-28T14:00:00Z' },
];

export const DEMO_TEMPLATES: QuestionnaireTemplate[] = [
  {
    id: 'qt1',
    name: 'Pre-Session Family Portrait Questionnaire',
    description: 'Gather important details before the family session',
    shoot_type: 'family',
    created_at: '2025-01-15T10:00:00Z',
    questions: [
      { id: 'q1', type: 'text', label: 'How many people will be photographed?', required: true },
      { id: 'q2', type: 'textarea', label: 'Tell us about your family', required: false, placeholder: 'Kids ages, personalities, etc.' },
      { id: 'q3', type: 'select', label: 'Preferred location style', required: true, options: ['Studio', 'Outdoor Park', 'Beach', 'Home', 'Urban'] },
      { id: 'q4', type: 'yesno', label: 'Do you have any specific poses in mind?', required: false },
      { id: 'q5', type: 'multiselect', label: 'Props you would like to include', required: false, options: ['Flowers', 'Balloons', 'Signs', 'Pets', 'Sports equipment', 'Musical instruments'] },
    ],
  },
  {
    id: 'qt2',
    name: 'Wedding Day Worksheet & Questionnaire',
    description: 'Complete wedding day planning questionnaire',
    shoot_type: 'wedding',
    created_at: '2025-02-01T10:00:00Z',
    questions: [
      { id: 'q1', type: 'text', label: 'Ceremony venue and address', required: true },
      { id: 'q2', type: 'text', label: 'Reception venue and address', required: true },
      { id: 'q3', type: 'date', label: 'Wedding date', required: true },
      { id: 'q4', type: 'number', label: 'Estimated guest count', required: true },
      { id: 'q5', type: 'textarea', label: 'Must-have shots list', required: false },
      { id: 'q6', type: 'yesno', label: 'Are you doing a first look?', required: true },
      { id: 'q7', type: 'multiselect', label: 'Family formal groupings needed', required: false, options: ['Bride + Parents', 'Groom + Parents', 'Full family', 'Siblings', 'Grandparents', 'Extended family'] },
    ],
  },
  {
    id: 'qt3',
    name: 'Senior Portrait Questionnaire',
    description: 'Help seniors express their personality',
    shoot_type: 'senior',
    created_at: '2025-03-01T10:00:00Z',
    questions: [
      { id: 'q1', type: 'text', label: 'School name', required: true },
      { id: 'q2', type: 'select', label: 'Preferred outfit count', required: true, options: ['1 outfit', '2 outfits', '3 outfits', '4+ outfits'] },
      { id: 'q3', type: 'multiselect', label: 'Hobbies / Interests to showcase', required: false, options: ['Sports', 'Music', 'Art', 'Dance', 'Academics', 'Vehicles', 'Pets'] },
      { id: 'q4', type: 'yesno', label: 'Do you want cap & gown photos?', required: true },
      { id: 'q5', type: 'textarea', label: 'Anything else we should know?', required: false },
    ],
  },
];

export const DEMO_ACTIVITIES: ActivityLog[] = [
  { id: 'a1', action: 'created', entity_type: 'lead', entity_name: 'Jessica & David', user_name: 'Alex Morgan', created_at: '2025-04-20T10:00:00Z' },
  { id: 'a2', action: 'updated status to', entity_type: 'lead', entity_name: 'Emma Thompson', user_name: 'Sarah Chen', created_at: '2025-04-19T09:00:00Z' },
  { id: 'a3', action: 'sent proposal for', entity_type: 'lead', entity_name: 'The Rodriguez Family', user_name: 'Alex Morgan', created_at: '2025-04-22T16:00:00Z' },
  { id: 'a4', action: 'signed contract for', entity_type: 'lead', entity_name: 'Mark & Lisa', user_name: 'Sarah Chen', created_at: '2025-04-25T10:00:00Z' },
  { id: 'a5', action: 'uploaded', entity_type: 'document', entity_name: 'Invoice #2045', user_name: 'Alex Morgan', created_at: '2025-04-15T14:30:00Z' },
  { id: 'a6', action: 'converted to job', entity_type: 'lead', entity_name: 'Rachel Green', user_name: 'Alex Morgan', created_at: '2025-04-28T14:00:00Z' },
];

export const DEMO_STATS: DashboardStats = {
  new_leads: 2,
  active_jobs: 4,
  pending_invoices: 23,
  monthly_revenue: 4200,
  leads_change: 12,
  jobs_change: 5,
  invoices_change: -8,
  revenue_change: 18,
};
